pathvars:
  ids_loc: "/msherlock/inputs/valid_ids.csv"
  msd_config_loc: "/msherlock/msdconfig/test.yaml"

  # True outputs of process
  input_loc: "results/geometry/snakemake/all" # TODO: this is a vestige..
  output_loc: "results/geometry/snakemake/all" # TODO change to match others..

  models_loc: "results/eplus/snakemake/all"
  results_loc: "results/analysis/snakemake/all"

## start and stop for selecting cases to analyze
start_ix: 0
num_items: 5000
